### ISSUE TITLE
Drag handler is missing after dialog is reopened in Android

### ISSUE THREAD

**Issue by Qing-Novel** [readest/readest#1036]
## Bug Description

When opening the 'About' button, you can find a horizontal line on the top of the phone. Press and slide down to close the 'About' interface. But when you finish the operation, you can see a flash of the screen about the interface. At this time, when you open the About Interface again, the horizontal line runs to the status bar. Dragging at this time will only pull down the status bar

https://github.com/user-attachments/assets/55a547dc-5efd-4271-b733-b87b94aed2d0

## Expected behavior

A clear and concise description of what the expected behavior is.

**Example:**

```
The blank square should be transparent (invisible)
```

## Technical inputs

Operating System:aosp12

Readest Version:0.9.38

**Example:**

```
Operating System: macOS 14.3.1
Readest Version: 0.9.0
We are displaying custom scrollbars that disappear when the user is not scrolling. See ScrollWrapper.
Probably fixable with CSS
```

**Comment by chrox** [comment]
Please remove the example part in your issue ticket. It acts as an example in the templates.

**Comment by Qing-Novel** [comment]
> Please remove the example part in your issue ticket. It acts as an example in the issue template.

Deleted it

**Comment by chrox** [comment]
More important information is the screenshot of your About page which has the version of the webview. If it's possible, please upgrade the system Android WebView to the latest version (version 135.0). Some older WebView has compatibility problem which cannot fixed in the app's side. And we may not support older WebView version in the future.

**Comment by chrox** [comment]
`Expected behavior` and `Technical inputs` also have example parts. Please keep the issue ticket well organized.

**Comment by Qing-Novel** [comment]
> `Expected behavior` and `Technical inputs` also have example parts. Please keep the issue ticket well organized.

OK

**Comment by Qing-Novel** [comment]
At present, it seems that only the interface will have this issue

https://github.com/user-attachments/assets/28d520fa-9500-4dc3-b01c-822bd418a552

**Comment by Qing-Novel** [comment]
it still have this problem

https://github.com/user-attachments/assets/5d39c482-794d-4a91-8e9a-650b11260215
